[package]
name = "aletheia"
version = "0.1.0"
authors = ["Nicholas Yang <ny585@nyu.edu>"]
edition = "2018"

[dependencies]
reqwest = "0.9.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.4.10"
failure = "0.1.5"
failure_derive = "0.1.5"
chrono = "0.4"
rocket = "0.4.0"
rocket_contrib = "0.4.0"
itertools = "0.8"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"